name: Push File(or Dir) to another repository

on: push

jobs:

  repos-reader:
    runs-on: ubuntu-latest
    name: Repos read-yaml
    steps:
      - uses: actions/checkout@v1

      - name: Run read-yaml action
        id: yaml-data
        uses: KJ002/read-yaml@main      # You may wish to replace main with a version tag such as '1.6' etc.
        with:
          file: './repos.yaml'          # File to read from
          key-path: '["java-repos"]' # Access the runs key then the using key and retuns the value.

      - name: Display read-yaml output
        run: echo "${{ steps.yaml-data.outputs.data }}"


  copy-file:
    strategy:
      matrix:
        repos: 
          - "mytutor1"
          - "service-account-terraform"

    runs-on: ubuntu-20.04
    steps:
      - name: Clone Main Repo
        uses: actions/checkout@v2

      - name: Clone Repo to update
        uses: actions/checkout@v2
        with:
          repository: "DwijeshMishra/${{ matrix.repos }}"
          branch: "master"
          token: "{{ secrets.API_TOKEN_GITHUB }}"
      
      - name: Replace file to another repo
        env:
          repo_name: "{{ matrix.repos }}"
        run: | 
          cp -r ./project-specific.yaml ./DwijeshMishra/$repo_name/

      - name: Push to repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: feature/$GITHUB_SHA
          message: "Update project-specific.yaml $repo_name by github action"
          # push_options: '--force'
          
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
