name: Push File(or Dir) to another repository

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Push to another repo
      run: | 
          chmod +x bash.sh
          sudo ./bash.sh
