name: Push File(or Dir) to another repository

on: push


jobs:
  copy-file:
    strategy:
      matrix:
        repos: 
          - "mytutor1"
          - "service-account-terraform"

    runs-on: ubuntu-20.04
    steps:
      - name: Clone Main Repo
        uses: actions/checkout@v2

      - name: Clone Repo to update
        uses: actions/checkout@v2
        with:
          repository: "DwijeshMishra/${{ matrix.repos }}"
          path: "${{ matrix.repos }}"
          token: "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"
      
      - name: test2
        run: |
          ls
          cp -r $GITHUB_WORKSPACE/project-specific.yaml $GITHUB_WORKSPACE//${{ matrix.repos }}/
          tree ./
          cd $GITHUB_WORKSPACE//${{ matrix.repos }}/
          git remote -v

      - name: Push to repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: feature/$GITHUB_SHA
          commit_message: "Update project-specific.yaml $repo_name by github action"
          repository: ${{ github.workspace }}/${{ matrix.repos }}
          # push_options: '--force'

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v4
      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
